apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: mysecret-sops
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:8RpxKrnBwKPQc9tnEkdO,iv:cp5hDHlg6aTKGRC8fLrbhEvC5IcPMr703W/QmD2Vqvc=,tag:X4hMVPhOu/U2Gd5hbn/hbQ==,type:str]
          labels:
            label1: ENC[AES256_GCM,data:cDYwzkLc,iv:1Tql8K1SnmQy1uOhc/FxAXr2/+UaRoEXSlUWNUMfW8k=,tag:hXFsDiAWhKJtKv7qujNUNA==,type:str]
          annotations:
            key1: ENC[AES256_GCM,data:4ZPKfKTa,iv:6nrokKdu43baleAxQ0BCUYkoBZTetXDXY9r0grXJyJM=,tag:kwNQ7r9oGL2EQuzNlLUzUg==,type:str]
          data:
            user: ENC[AES256_GCM,data:4GoKnpjZE/hAqxYH1EfD1ReH7TbYNCzK,iv:j3tzs4tKfaU0VAM8R0zCh1RrucHSG49CmIRwmY6toxk=,tag:nRl1QKcPT6338s46OEc0kA==,type:str]
            password: ENC[AES256_GCM,data:pTINuyo/V5pjugeYziIwIrpKsMBDQlRv,iv:HWbxK0RDh8cZJvorGGS23g1WiMszCi/lNbpWUjdI52o=,tag:PhzE7e4eUlhD15xZ4XoEhw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19tfqxgdgx3fe96j8fyy0c65nsfj8ku8sl4ccfxnzpn3xpakylg5s8sgac7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmVG5sQVllY2JTZFdhaFlL
            bkN2UllNU3I5ay9lQUxuOHZXQXBEdTVYOWpnCnBsRkVSNzJENEZieDFWTXNLTUNN
            aTREMmR5MEI3a2IvWnFRYmpUMTZHd2sKLS0tIE80MDMvK2Jvb1pPd3BZb1VoU2VT
            VVE1bG5rV0FCc1hraU1VWW95OTNkZlUK2bW0EIgUr/cVcPtvD7PF8m5jCF6G/7e1
            wc8GYQWYYjDFvG1xYOKnwmJkizz+AVOvndoD9snFVbQjnBWupOK+Lg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-24T08:01:11Z"
    mac: ENC[AES256_GCM,data:bD1J3yDZUjLOUXUu+kA/e8EbvagpzwVHjQwlSPnWZyGGy7ARXafEh2yLFMZaB61JIWY8/SfijERBU3M09dv7UgoNsFhMT+WU1uS23DS4oVnaanLAVk1wvWhqcba/rMknt8zncv/kzVhgUI3wXF05f3Pu96x+AOjOdVJjt29FFpE=,iv:cbOE0pjEo/S3ASxLaqI9NgyiQ1DmXt0+vuri1kkOjuE=,tag:8ZCAzHFvAo3Tat6v9gLEtw==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.9.1
